apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
  labels:
    shyunn.io.instance: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: registry.cn-hangzhou.aliyuncs.com/shyunn/app:latest
          ports:
            - containerPort: 4000
              name: app-port
      restartPolicy: Always